[tool.ruff]
tab-size = 4

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"
indent-style = "space"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:datetime.datetime.utcfromtimestamp\\(\\) is deprecated:DeprecationWarning",
]
